# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 20:48
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(help_text='This is a help text', null=True, verbose_name='My video'),
        ),
    ]
