# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 17:31
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180109_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='technique_sub_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='technique_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(help_text='This is a help text', verbose_name='My video'),
        ),
    ]
