# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180111_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
